<?php

namespace Reneiw\Azuma;

use Reneiw\Azuma\Contracts\BasicAuthInterface;
use Reneiw\Azuma\Contracts\OAuthInterface;
use Reneiw\Azuma\Traits\BasicAuthTrait;
use Reneiw\Azuma\Traits\OAuthTrait;
use Reneiw\Azuma\Traits\VerificationTrait;

class Shopify extends API implements BasicAuthInterface, OAuthInterface
{
    use BasicAuthTrait;
    use OAuthTrait;
    use VerificationTrait;

    public const HEADER_REST_API_LIMITS = 'HTTP_X_SHOPIFY_SHOP_API_CALL_LIMIT';
    public const HEADER_ACCESS_TOKEN = 'X-Shopify-Access-Token';

    public ?string $version;

    public function __construct(array $data = [])
    {
        switch (true) {
            case !empty($data['token']):
                $this->useOAuth($data);
                break;
            case (!empty($data['username']) && !empty($data['password'])):

                $this->useBasicAuth();
                break;
            default:
                break;
        }
        parent::__construct($data);
    }

    public function getVersion(): ?string
    {
        return !empty($this->version) ? $this->version : null;
    }

    public function setVersion(string $version): Shopify
    {
        $this->version = $version;
        return $this;
    }

    public function request(string $method, string $uri, array $params = null, array $headers = [], bool $sync = true)
    {
        return parent::request($method, $uri, $params, $headers, $sync); // TODO: Change the autogenerated stub
    }
}
